### PR TITLE
add fee estimates to block explorer

### PR DESCRIPTION
**Pull request by acityinohio**
Unfortunately couldn't test in my local env (need to figure out how to get that working eventually), but with the addition to the python sdk I think this should work. Let me know what you think, and thanks!

### CODE REVIEW

**Comment by acityinohio** [comment]
Awesome, thanks!

**Comment by mflaxman** [comment]
Looks great! The only change I made was to update the reference to the python library to be the latest version (https://github.com/blockcypher/explorer/commit/52a4ed5e6e36b74c4a39afccc0073129ea779b44).

I think the per kilobyte fee estimate is very confusing to the average user who comes across this for the first time, some ideas:
- Link to the docs where this is explained (assuming we have a page that does this)
- Also show what this would be for an "average" transaction, though this is obviously not a very accurate measure.

I think 95% of people who look at this will read it and assume that if your transaction fee is the amount referenced in "High Priority" then your tx will go through in 1-2 blocks. That's wrong.

**Comment by mflaxman** [comment]
I just pushed a small change @acityinohio (https://github.com/blockcypher/explorer/commit/872a003c6f6372fdd0627b20df7fb3a44370d20a), what do you think? It should be live on the site in a few moments.

Definitely open to a much bigger one (or any changes really), just was going for a small tweak that might make it more clear. UI is hard!

**Comment by acityinohio** [comment]
Ah great points Michael. There are two pages in the docs that might be relevant: the [blockchain object page](http://dev.blockcypher.com/#blockchain) and the [customizing transaction page](http://dev.blockcypher.com/#customizing-transaction-requests). Customizing transaction page is probably most explicit. Really like the idea of an "average" transaction too. Maybe as another row?

**Comment by acityinohio** [comment]
Ah very good! I like that change a great deal.

**Comment by acityinohio** [comment]
What are you thinking in terms of average transaction? One thought: an additional row showing "fee/250 bytes." 

Another, potentially better thought: get rid of "KB" altogether and just make it titled "Fee for Average Transactions" then add in the paragraph "fees are based on transaction size; average transaction size is 250 bytes." Then those who want to do the KB calculation can just multiply by 4, if they feel so inclined.

**Comment by matthieu** [comment]
Instead of a single "avg transaction" number I'd take a range. I hate the
"average tx" metric as it leads to all the surprises users hate when their
tx was generated with 5 inputs. So I'd give a range to goes between a 250
bytes tx to 1kb tx.

**Comment by acityinohio** [comment]
Ah cool, that's a good idea. @mflaxman , how about 250 bytes, 500 bytes, 750 bytes, 1 KB? Then make a new column on the left called "TX Size," and change the header to "Fee Estimates" instead of "Fee Estimates Per Kilobyte"

**Comment by matthieu** [comment]
You could "simplify" to number of inputs too but I'm not sure that's an
actual simplification.

**Comment by mflaxman** [comment]
@matthieu and @acityinohio what do you think now? (see https://live.blockcypher.com/btc-testnet/)

I didn't include the link to the docs because it doesn't say anything more and I don't think it's more clear.

If a big TX can be 1kb, then I'm ok with some people mis-understanding and using the btc/KB metric even though they could get away with a bit less (it's the upper-bound we're displaying anyway).

**Comment by acityinohio** [comment]
Cool! I like the info button highlight.

General question for everyone: maybe it makes sense to show fees in mBTC/"bits"? Just to get granularity. Or maybe extend rounding to more than 4 decimals (5-6 decimals perhaps?).

Both have their pros/cons...I think I'd opt more for mBTC or bits, but I'm not sure what's best for a typical user.

**Comment by mflaxman** [comment]
@acityinohio I think you're right so I just added an extra decimal place and pushed (https://github.com/blockcypher/explorer/commit/2c354b060f7600cfcfc2d8dfbbeb4014d22849bb).

Re units, I want to redo that completely (probably similar to how blockchain.info does it). There's a ticket for that here:
https://github.com/blockcypher/explorer/issues/100

This is a tooltip so slightly different but will probably be covered then as well.

**Comment by matthieu** [comment]
Can you not round then?

Also what about a link to the endpoint (like
https://api.blockcypher.com/v1/btc/main), as-is a developer wouldn't know
where to go to get the data.

**Comment by acityinohio** [comment]
Nice! Yeah, that makes sense to have it be adaptive, but I think the added decimal place ameliorates things for the time being. Good work @mflaxman!

**Comment by pml10628** [comment]
1ede817398a84d4c8533f423444681cf
pml106288@aol.com

**Comment by zhtet036** [comment]
1C76qHBjywP7vNbyzhvKsnvoouTHa1Vtx

**Pull request merged**
