### PR TITLE
Login

### PR DESCRIPTION
**Pull request by bezlogina89**

### CODE REVIEW

**Comment by abdultelicmohamed** [comment]
Hi may name is abdultelic please I need help

**Comment by suiody** [comment]
كيف لي خدمتك

**Comment by Sittinan** [comment]
ทำไมๆม่ส่งbtcกลับมาถึงฉัน

**Comment by Amin2110** [comment]
Pay

**Comment by quentinlesceller** [comment]
Thank you for the PR! Unfortunately, I don't see what would be the benefits of having a login page in the explorer since there is already a dashboard on BlockCypher.com. Closing thanks again.

**Pull request closed without merging**
